---
- name: Configure Database With Docker Image
  hosts: database
  remote_user: ubuntu
  become: yes
  vars:
    ansible_ssh_timeout: 60
    default_container_name: Foo App Database
    default_container_image: postgres:14.7

  # Adapated from Digital Ocean's Docker Installation Via Ansible on Ubuntu Guide https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-22-04
  tasks:
    - name: Install Aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install Required System Packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true


    - name: Pull App Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create Foo App Container
      community.docker.docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: present
        environment:
          POSTGRES_PASSWORD: devops
          POSTGRES_USER: pete
          POSTGRES_DB: foo
        volumes:
          - ..devops/misc/snapshot-prod-data.sql